[<img align="right" width="200" height="200" src="https://www.tu-braunschweig.de/typo3conf/ext/tu_braunschweig/Resources/Public/Images/Logos/tu_braunschweig_logo.svg">](https://www.tu-braunschweig.de/en/)

[Mehdi Maboudi](https://www.tu-braunschweig.de/en/igp/staff/mehdi-maboudi) ([m.maboudi@tu-bs.de](m.maboudi@tu-bs.de))

[Technical University of Braunschweig](https://www.tu-braunschweig.de/en/)  
[Institute of Geodesy and Photogrammetry](https://www.tu-braunschweig.de/igp)  
***

Considering _Tom Mitchell_ definition:  
A computer program is said to learn from experience 𝐸 with respect to some task T and some
performance measure 𝑃, if its performance on 𝑇, as measured by 𝑃, improves with experience 𝐸

<font color='red'>## E1 (12 pnt)</font>

Select 4 machine learning applications and answer the following questions:
- **Task(T)**
- **Experience(E)**
- **Measure Performance(P)**
***

**Example from the lecture:**

**Applications**: Spam filtering
  
- **Task(T)**: The task is to learn how to classify emails as spam or ham(non-spam).
- **Experience(E)**: The dataset is a set consisting of emails and their labels (spam or ham).
- **Measure Performance(P)**: count the number of correct predictions to asses the prediction accuracy.

_**Category**_. Since we are looking for 2 class labels (spam, non-spam), this is a supervised binary classification.
***

**Applications01**: performance analysis
  
- **Task(T)**: project a company's performance in the next years
- **Experience(E)**: The dataset contains e.g. number of sold products, stock prices, sum of investments, profits
- **Measure Performance(P)**: comparation of training samples from other companys and their performance with the new company

_**Category**_. Regression  
***

**Applications02**: product recommendations
  
- **Task(T)**: recommend products to clients who have already bought similar products
- **Experience(E)**: recently bought products and shopping habits
- **Measure Performance(P)**: clustering bought products to find similar products for the recommendation--> performance can be measured by the clients next purchases
_**Category**_. Classification
***

**Applications03**: Deleting offensive comments on social media
  
- **Task(T)**: Finding comments with e.g. rassist, homophobic content
- **Experience(E)**: former social media comments with sentences that are not allowed
- **Measure Performance(P)**: searching for keywords or sentences that should be deleted-->checking the performance by analyzing new comments and whether they were found

_**Category**_. Classification
***

**Applications04**: Cancer diagnosis
  
- **Task(T)**: Find skin changes that might be skin chancer
- **Experience(E)**: photos with of examples for skin cancer and photos with normal skin changes
- **Measure Performance(P)**: check the number of correct cancer predictions and mistakes

_**Category**_. Classification
***

<font color='red'>## E2 (20 pnt)</font>

Standardization of a dataset is a common requirement for many machine learning estimators: they might behave badly if the individual features do not more or less look like standard normally distributed data (e.g. Gaussian with 0 mean and unit variance).  
In this Exercise we will write a very simplified and naive feature normalizer

Given the function below called `normalizer` do the following step:
 - **ducumentation** (4pnts)
 - **function implementation** (12pnts)  
      Normalizing the elements of a 2D array:
    
            For each element of a column:
            Subtract the mean and devide it by variance (this is called Centering and scaling)

            Considering "i"th element of "j"th column of array X as x[i,j],
            transforme x[i,j] to z[i,j]:

            z[i,j] = (x[i,j] - u) / s

            where u is the mean of the column j and s is the standard deviation of that column.
 - **test your function** (4pnts). Do not forget edge cases
      
You can get some hints from folowing link:   
**But do not use it directly and write your code just with low level numpy and python commands**  
[sklearn.preprocessing.StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)

In [24]:
import numpy as np
def normalizer(X,):
    """
    Documentation:
        function description: the function subtracts the mean of the column from each element and divides each element by the variance
        inputs: 2D-array X[i,j]
        outputs: mean u, standard deviation s and 2D-array X_transformed[i,j]
    """
    ### Start of your code ##

    # check the inputs
    if X.ndim!=2:
      raise ValueError("wrong dimension of matrix X")
    # main body
    u=np.mean(X, axis=1)
    s=np.std(X, axis=1)
    #column or row wise, otherwise: axis=0??
    s[s==0]=1

    X_transformed=(X-u)/s
    ### End of your code ##
    return X_transformed




Add your tests in separate cells

In [25]:
#test01: division by 0 if s==0(array with similar values):
test_array=np.ones((3,3))
normalizer(test_array)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
#test01:
new_array=np.arange(1,10).reshape(3,3)
print(new_array)
normalizer(new_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[-1.22474487, -3.67423461, -6.12372436],
       [ 2.44948974,  0.        , -2.44948974],
       [ 6.12372436,  3.67423461,  1.22474487]])

<font color='red'>## E3 (30 pnt)</font>  
Transform features by scaling each feature to a given range.

Write a function to transform features by scaling each feature to a given range.

- Understanding the problem(10)  
- Documentation (4pnts)  
- Function implementation (12pnts)  
- Test your function (4pnts)
- selecting proper name for function and variables (3pnts)

You should check the following link to understand the problem:  
**But do not use it directly and write your code just with low level numpy and python commands**  
[sklearn.preprocessing.MinMaxScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html)

In [53]:
"""Documentation
function description: function scales each feature to a given range (e.g. [0,1]) columnwise
inputs: 2D array; given range e.g.(0,1)
outputs: scaled 2D array
"""
def scaler (X, given_range=(0,1)):
  # check the inputs
  if X.ndim!=2:
    raise ValueError("wrong dimension of matrix X")

  X_min=X.min(axis=0)
  X_max=X.max(axis=0)
  new_min,new_max=given_range

  #division by 0
  zero_range=X_min-X_max==0
  X_min[zero_range]=X_max[zero_range]-1

  #scaling
  X_scaled=((X-X_min)/(X_max-X_min))*(new_max-new_min)+new_min
  return X_scaled

#test01:
scaler(new_array)

#test02: array with minimum and maximum smaller than the given range
another_array=np.array([[0.3,0.55,0.6],[0.44,0.88,0.50],[0.2,0.3,0.4]])
print(another_array)
scaler(another_array)

#test03: array with wrong dimension
another_array2=np.arange(8).reshape(2,2,2)
print(another_array2)
scaler(another_array2)

#test04: array with one single value:
another_array3=np.ones(9).reshape(3,3)
print(another_array3)
scaler(another_array3)


[[0.3  0.55 0.6 ]
 [0.44 0.88 0.5 ]
 [0.2  0.3  0.4 ]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


ValueError: wrong dimension of matrix X